// Generated by CoffeeScript 1.10.0
(function() {
  var Action, fireByResult, makeNodeCb, makeQueryStrR, spawn;

  fireByResult = function(cb, data) {
    if (data instanceof Action) {
      return data._go(cb);
    } else {
      return cb(data);
    }
  };

  Action = (function() {
    function Action(_go1) {
      this._go = _go1;
    }

    Action.prototype._next = function(cb) {
      var _go;
      _go = this._go;
      return new Action(function(_cb) {
        return _go(function(data) {
          return fireByResult(_cb, cb(data));
        });
      });
    };

    Action.prototype.next = function(cb) {
      var _go;
      _go = this._go;
      return new Action(function(_cb) {
        return _go(function(data) {
          if (data instanceof Error) {
            return _cb(data);
          } else {
            return fireByResult(_cb, cb(data));
          }
        });
      });
    };

    Action.prototype.guard = function(cb) {
      var _go;
      _go = this._go;
      return new Action(function(_cb) {
        return _go(function(data) {
          if (data instanceof Error) {
            return fireByResult(_cb, cb(data));
          } else {
            return _cb(data);
          }
        });
      });
    };

    Action.prototype.go = function(cb) {
      return this._go(function(data) {
        if (data instanceof Error) {
          throw data;
        } else if (cb != null) {
          return cb(data);
        }
      });
    };

    return Action;

  })();

  Action.wrap = function(data) {
    return new Action(function(cb) {
      return cb(data);
    });
  };

  Action.freeze = function(action) {
    var callbacks, data, pending, ret;
    pending = true;
    data = void 0;
    callbacks = [];
    ret = action._go(function(_data) {
      var cb, j, len;
      if (pending) {
        data = _data;
        pending = false;
        for (j = 0, len = callbacks.length; j < len; j++) {
          cb = callbacks[j];
          cb(_data);
        }
        return callbacks = void 0;
      }
    });
    return new Action(function(cb) {
      if (pending) {
        callbacks.push(cb);
      } else {
        cb(data);
      }
      return ret;
    });
  };

  Action.safe = function(err, fn) {
    return function(data) {
      var e, error;
      try {
        return fn(data);
      } catch (error) {
        e = error;
        return err;
      }
    };
  };

  Action.safeRaw = function(fn) {
    return function(data) {
      var e, error;
      try {
        return fn(data);
      } catch (error) {
        e = error;
        return e;
      }
    };
  };

  Action.chain = function(monadicActions) {
    return function(init) {
      var a, j, len, monadicAction, ref;
      if (monadicActions.length > 0) {
        a = monadicActions[0](init);
        ref = monadicActions.slice(1);
        for (j = 0, len = ref.length; j < len; j++) {
          monadicAction = ref[j];
          a = a.next(monadicAction);
        }
        return a;
      } else {
        return Action.wrap(void 0);
      }
    };
  };

  Action.repeat = function(times, action, stopAtError) {
    var a;
    if (stopAtError == null) {
      stopAtError = false;
    }
    return a = action._next(function(data) {
      if (((data instanceof Error) && stopAtError) || times-- === 0) {
        return data;
      } else {
        return a;
      }
    });
  };

  Action.delay = function(delay, action) {
    return new Action(function(cb) {
      return setTimeout(cb, delay);
    })._next(function() {
      return action;
    });
  };

  Action.retry = function(times, action) {
    var a;
    return a = action.guard(function(e) {
      if (times-- !== 0) {
        return a;
      } else {
        return new Error('RETRY_ERROR: Retry limit reached');
      }
    });
  };

  Action.parallel = function(actions, stopAtError) {
    var l;
    if (stopAtError == null) {
      stopAtError = false;
    }
    l = actions.length;
    if (l > 0) {
      return new Action(function(cb) {
        var action, countDown, fireByIndex, i, j, len, results;
        countDown = l;
        results = new Array(countDown);
        fireByIndex = function(index) {
          return function(data) {
            if ((data instanceof Error) && stopAtError) {
              cb(data);
              return countDown = -1;
            } else {
              results[index] = data;
              if (--countDown === 0) {
                return cb(results);
              }
            }
          };
        };
        for (i = j = 0, len = actions.length; j < len; i = ++j) {
          action = actions[i];
          action._go(fireByIndex(i));
        }
        return void 0;
      });
    } else {
      return Action.wrap([]);
    }
  };

  Action.join = function(action1, action2, cb2) {
    return new Action(function(cb) {
      var countDown, result1, result2;
      result1 = result2 = void 0;
      countDown = 2;
      action1._go(function(data) {
        result1 = data;
        countDown--;
        if (countDown === 0) {
          return fireByResult(cb, cb2(result1, result2));
        }
      });
      action2._go(function(data) {
        result2 = data;
        countDown--;
        if (countDown === 0) {
          return fireByResult(cb, cb2(result1, result2));
        }
      });
      return void 0;
    });
  };

  Action.race = function(actions, stopAtError) {
    if (stopAtError == null) {
      stopAtError = false;
    }
    return new Action(function(cb) {
      var action, countDown, i, j, len, results1;
      countDown = actions.length;
      if (countDown === 0) {
        return cb(new Error('RACE_ERROR: All actions failed'));
      } else {
        results1 = [];
        for (i = j = 0, len = actions.length; j < len; i = ++j) {
          action = actions[i];
          action._go(function(data) {
            countDown--;
            if ((!(data instanceof Error)) || stopAtError) {
              if (typeof cb === "function") {
                cb(data);
              }
              cb = void 0;
              return countDown = -1;
            } else if (countDown === 0) {
              return cb(new Error('RACE_ERROR: All actions failed'));
            }
          });
          results1.push(void 0);
        }
        return results1;
      }
    });
  };

  Action.sequence = function(actions, stopAtError) {
    var chainByIndex, l;
    if (stopAtError == null) {
      stopAtError = false;
    }
    l = actions.length;
    chainByIndex = function(a, action, index, results) {
      return a._next(function(data) {
        if ((data instanceof Error) && stopAtError) {
          return data;
        } else {
          results[index] = data;
          return action;
        }
      });
    };
    return new Action(function(cb) {
      var a, action, i, j, len, ref, results;
      results = new Array(l);
      if (l > 0) {
        a = actions[0];
        ref = actions.slice(1);
        for (i = j = 0, len = ref.length; j < len; i = ++j) {
          action = ref[i];
          a = chainByIndex(a, action, i, results);
        }
        return a._go(function(data) {
          if ((data instanceof Error) && stopAtError) {
            return cb(data);
          } else {
            results[l - 1] = data;
            return cb(results);
          }
        });
      } else {
        return cb(results);
      }
    });
  };

  makeNodeCb = function(cb) {
    return function(err, data) {
      return cb(err ? err : data);
    };
  };

  Action.makeNodeAction = function(nodeAPI) {
    return function(a, b, c) {
      var _go, args, i, l, self;
      self = this;
      l = arguments.length;
      switch (l) {
        case 0:
          _go = function(cb) {
            return nodeAPI.call(self, makeNodeCb(cb));
          };
          break;
        case 1:
          _go = function(cb) {
            return nodeAPI.call(self, a, makeNodeCb(cb));
          };
          break;
        case 2:
          _go = function(cb) {
            return nodeAPI.call(self, a, b, makeNodeCb(cb));
          };
          break;
        case 3:
          _go = function(cb) {
            return nodeAPI.call(self, a, b, c, makeNodeCb(cb));
          };
          break;
        default:
          i = l;
          args = new Array(l + 1);
          while (i-- > 0) {
            args[i] = arguments[i];
          }
          _go = function(cb) {
            args[l] = makeNodeCb(cb);
            return nodeAPI.apply(self, args);
          };
      }
      return new Action(_go);
    };
  };

  spawn = function(gen, action, cb) {
    return action._go(function(v) {
      var done, nextAction, ref;
      if (v instanceof Error) {
        gen["throw"](v);
      }
      ref = gen.next(v), nextAction = ref.value, done = ref.done;
      if (done) {
        return cb(v);
      } else {
        return spawn(gen, nextAction, cb);
      }
    });
  };

  Action.co = function(genFn) {
    return function() {
      var gen;
      gen = genFn.apply(this, arguments);
      return new Action(function(cb) {
        return spawn(gen, gen.next().value, cb);
      });
    };
  };

  makeQueryStrR = function(prefix, data) {
    var k, key, result, v;
    result = [];
    for (k in data) {
      v = data[k];
      key = prefix ? prefix + '[' + k + ']' : k;
      if ((typeof v) === 'object') {
        result.push(makeQueryStrR(key, v));
      } else if (v != null) {
        result.push(encodeURIComponent(key) + "=" + encodeURIComponent(v));
      }
    }
    return result.join('&');
  };

  Action.param = function(data) {
    return makeQueryStrR('', data);
  };

  Action.jsonp = function(opts) {
    return new Action(function(cb) {
      var callbackName, script;
      callbackName = 'callback_' + (Math.round(Math.random() * 1e16)).toString(36);
      script = document.createElement('script');
      window[callbackName] = function(resp) {
        script.parentNode.removeChild(script);
        cb(resp);
        return window[callbackName] = void 0;
      };
      script.onerror = function() {
        script.parentNode.removeChild(script);
        cb(new Error('REQUEST_ERROR: error when making jsonp request'));
        window[callbackName] = void 0;
        return false;
      };
      script.onload = function() {
        return false;
      };
      script.src = opts.url + (opts.url.indexOf('?') === -1 ? '?' : '&') + (opts.callback ? opts.callback : 'callback') + '=' + callbackName;
      script.callbackName = callbackName;
      document.body.appendChild(script);
      return script;
    });
  };

  Action.ajax = function(opts) {
    return new Action(function(cb) {
      var k, ref, v, xhr;
      xhr = new window.XMLHttpRequest;
      xhr.open(opts.method, opts.url, true, opts.user, opts.password);
      xhr.onload = function() {
        if (xhr.readyState === 4) {
          if (xhr.status >= 200 && xhr.status < 300) {
            if (opts.responseType != null) {
              return cb(xhr.response);
            } else {
              return cb(xhr.responseText);
            }
          } else {
            return cb(new Error('REQUEST_ERROR: status' + xhr.status));
          }
        }
      };
      ref = opts.headers;
      for (k in ref) {
        v = ref[k];
        xhr.setRequestHeader(k, v);
      }
      if (opts.timeout) {
        xhr.timeout = opts.timeout;
        xhr.ontimeout = function() {
          return cb(new Error('REQUEST_ERROR: timeout'));
        };
      }
      if (opts.responseType) {
        xhr.responseType = opts.responseType;
      }
      switch (typeof opts.data) {
        case 'string':
          xhr.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
          xhr.send(opts.data);
          break;
        case 'object':
          if (opts.data instanceof window.FormData) {
            xhr.send(opts.data);
          } else {
            xhr.setRequestHeader('Content-Type', 'application/json; charset=UTF-8');
            xhr.send(JSON.stringify(opts.data));
          }
          break;
        default:
          xhr.send();
      }
      return xhr;
    });
  };

  if ((typeof module !== "undefined" && module !== null) && (module.exports != null)) {
    module.exports = Action;
  } else if (typeof define === "function" && define.amd) {
    define(function() {
      return Action;
    });
  } else if (typeof window !== "undefined" && window !== null) {
    window.Action = Action;
  }

}).call(this);
