// Generated by CoffeeScript 1.10.0
var Action, dirTree, fs, lift, path, readDirA, statA;

Action = require('../Action');

lift = Action.makeNodeAction;

fs = require('fs');

readDirA = lift(fs.readdir);

statA = lift(fs.stat);

path = require('path');

dirTree = function(dirName) {
  return readDirA(dirName).next(function(fileNames) {
    return Action.parallel(fileNames.map(function(fileName) {
      var p;
      p = path.join(dirName, fileName);
      return statA(p).next(function(stat) {
        if (stat.isDirectory()) {
          return dirTree(p);
        } else {
          return p;
        }
      });
    }));
  });
};

dirTree('./').go(function(paths) {
  return console.log(paths.join('\n'));
});
